query EmployeePreviousWorks($where: EmployeePreviousWorkWhereInput, $orderBy: [EmployeePreviousWorkOrderByWithRelationInput!], $cursor: EmployeePreviousWorkWhereUniqueInput, $take: Int, $skip: Int, $distinct: [EmployeePreviousWorkScalarFieldEnum!]) {
  employeePreviousWorks(where: $where, orderBy: $orderBy, cursor: $cursor, take: $take, skip: $skip, distinct: $distinct) {
    id
    files
    link
    position
    title
    
  }
}

query EmployeePreviousWork($where: EmployeePreviousWorkWhereUniqueInput!) {
  employeePreviousWork(where: $where) {
    files
    description
    id
    link
    position
    title
  }
}