query Products(
  $where: ProductWhereInput
  $orderBy: [ProductOrderByWithRelationInput!]
  $cursor: ProductWhereUniqueInput
  $take: Int
  $skip: Int
  $distinct: [ProductScalarFieldEnum!]
) {
  products(
    where: $where
    orderBy: $orderBy
    cursor: $cursor
    take: $take
    skip: $skip
    distinct: $distinct
  ) {
    id
    images
    name
    price
    type
    slug
  }
}

query Product(
  $where: ProductWhereUniqueInput!
  $fetauresCategoriesWhere2: FetaureCategoryWhereInput
  $orderBy: [FetaureCategoryOrderByWithRelationInput!]
  $cursor: FetaureCategoryWhereUniqueInput
  $take: Int
  $skip: Int
  $distinct: [FetaureCategoryScalarFieldEnum!]
  $fetauresWhere2: ProductFetaureWhereInput
  $fetauresOrderBy2: [ProductFetaureOrderByWithRelationInput!]
  $fetauresCursor2: ProductFetaureWhereUniqueInput
  $fetauresTake2: Int
  $fetauresSkip2: Int
  $fetauresDistinct2: [ProductFetaureScalarFieldEnum!]
  $reveiwsWhere2: ReviewWhereInput
) {
  product(where: $where) {
    _count {
      reveiws(where: $reveiwsWhere2)
    }
    category {
      name
      slug
    }
    id
    description
    images
    name
    price
    employee {
      id
      image
      name
    }
    orderStartPrice
    slug
    type
    stock
    minimumOrderNeededToStart
    custom_product_status
    sizes
    fetauresCategories(
      where: $fetauresCategoriesWhere2
      orderBy: $orderBy
      cursor: $cursor
      take: $take
      skip: $skip
      distinct: $distinct
    ) {
      name
      id
      fetaures(
        where: $fetauresWhere2
        orderBy: $fetauresOrderBy2
        cursor: $fetauresCursor2
        take: $fetauresTake2
        skip: $fetauresSkip2
        distinct: $fetauresDistinct2
      ) {
        name
        id
        value
      }
    }
  }
}

query AggregateOrderItem(
  $where: OrderItemWhereInput
  $orderBy: [OrderItemOrderByWithRelationInput!]
  $cursor: OrderItemWhereUniqueInput
  $take: Int
  $skip: Int
) {
  aggregateOrderItem(
    where: $where
    orderBy: $orderBy
    cursor: $cursor
    take: $take
    skip: $skip
  ) {
    _sum {
      qty
    }
  }
}
